set-option -g default-command "reattach-to-user-namespace -l zsh"
set -g default-terminal "xterm-256color"
set -g terminal-overrides ',xterm-256color:Tc'
set-option -g renumber-windows on
unbind C-k # Using that for ack in vim
set -g history-limit 99999
set -s escape-time 50

bind c new-window -c "#{pane_current_path}"

# ----------------------
# Status Bar
# -----------------------
set-option -g status on                # turn the status bar on
set -g status-interval 15               # set update frequencey (default 15 seconds)
set -g status-justify left              # center window list for clarity

# visual notification of activity in other windows
setw -g monitor-activity on
set -g visual-activity on

set -g status-justify left
set -g status-bg default
set -g status-fg colour12
set -g status-interval 2

set -g status-position bottom
set -g status-bg colour234
set -g status-fg colour137
# set -g status-attr dim
set -g status-left '#(basename #{pane_current_path})'
set -g status-right '#[fg=colour233,bg=colour241,bold] %d/%m #[fg=colour233,bg=colour245,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour255]#W#[fg=colour50]#F '

setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour250]#W#[fg=colour244]#F '

# ----------------------
# Tabs
# ----------------------
set-option -g set-titles on
set-option -g set-titles-string "#S lol"

#---------------------
# New pane in same dir
#---------------------
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"

#--------------------
# copy paste a-la vim
#--------------------
bind-key -T copy-mode-vi 'v' send -X begin-selection
# bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
bind-key -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel 'reattach-to-user-namespace pbcopy'

#-------------
# Plugins list
#-------------
# List of plugins, type Leader I to reload list
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'off'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run  -b '~/.tmux/plugins/tpm/tpm'
