return {
  'folke/which-key.nvim',
  event = 'VimEnter',
  opts = {
    -- Delay between pressing a key and opening which-key (ms).
    -- Independent of `vim.o.timeoutlen`.
    delay = 0,
    icons = {
      mappings = vim.g.have_nerd_font,
      -- With a Nerd Font, `{}` uses which-key's default icons.
      keys = vim.g.have_nerd_font and {} or {
        Up = '<Up> ',
        Down = '<Down> ',
        Left = '<Left> ',
        Right = '<Right> ',
        C = '<C-…> ',
        M = '<M-…> ',
        D = '<D-…> ',
        S = '<S-…> ',
        CR = '<CR> ',
        Esc = '<Esc> ',
        ScrollWheelDown = '<ScrollWheelDown> ',
        ScrollWheelUp = '<ScrollWheelUp> ',
        NL = '<NL> ',
        BS = '<BS> ',
        Space = '<Space> ',
        Tab = '<Tab> ',
        F1 = '<F1>',
        F2 = '<F2>',
        F3 = '<F3>',
        F4 = '<F4>',
        F5 = '<F5>',
        F6 = '<F6>',
        F7 = '<F7>',
        F8 = '<F8>',
        F9 = '<F9>',
        F10 = '<F10>',
        F11 = '<F11>',
        F12 = '<F12>',
      },
    },
    -- Document existing key chains
    spec = {
      { '<leader>A', group = '[A]ider' },
      { '<leader>c', group = '[C]laude' },
      { '<leader>d', group = '[D]ocument' },
      { '<leader>h', group = 'Git [H]unk', mode = { 'n', 'v' } },
      { '<leader>p', group = '[P]i' },
      { '<leader>ob', group = '[Ob]sidian' },
      { '<leader>r', group = '[R]ename' },
      { '<leader>s', group = '[S]earch' },
      { '<leader>b', group = '[B]reakpoint/Debug' },
      { '<leader>t', group = '[T]oggle' },
      { 'm', group = 'Book[m]arks' },
    },
  },
}
