-- require("lspconfig").solargraph.setup({
-- 	cmd = { "docker-compose", "run", "-t", "-p", "7658:7658", "--rm", "app", "solargraph", "stdio" },
-- 	settings = {
-- 		solargraph = {
-- 			transport = "stdio",
-- 			-- transport = "external",
-- 			-- externalServer = {
-- 			-- 	host = "localhost",
-- 			-- 	port = 7658
-- 			-- },
-- 			diagnostics = true,
-- 			init_options = {
-- 				formatting = true
-- 			}
-- 		}
-- 	}
-- })
--
-- NOTE this seems to be doing the trick
-- https://github.com/autozimu/LanguageClient-neovim/blob/next/INSTALL.md
--
--
-- XXX this guy may have a solution https://critchlow.xyz/2021/12/03/solargraph.html
