# workmux config template to include in subdirectories (monorepos for ex)
nerdfont: true # Enable nerdfont icons (prompted on first run)
merge_strategy: rebase # Make workmux merge do rebase by default
agent: $DEFAULT_AI_AGENT
mode: session

files:
  symlink:
    - "<global>"

windows:
  - name: editor
    panes:
      - command: nvim
  - name: agent
    panes:
      - command: <agent>
  - name: shell
    panes:
      - {}
    focus: true

post-create:
  - "<global>"
